export const PublicationsData = [
    {
        aKey: "journal",
        title: "Journal Publications",
        content: [
            "Khaleghi, H., & Karatas, A. (2024). Assessing the Dynamic Thermal Performance of Prefabricated Wall Panels in Extreme Hot Weather Conditions. Journal of Building Engineering, 108351.",
            "Palani, H., & Karatas, A. (2024). Investigating the Disparities between Experimental and Computational Analyses of Thermal Performance in Prefabricated Wall Panels. Applied Thermal Engineering, 121568.",
            "Khaleghi, H., & Karatas, A. (2024). Assessing the Dynamic Thermal Performance of Prefabricated Wall Panels in Extreme Hot Weather Conditions. Journal of Building Engineering, 82, 108351.",
            "Palani, H., Acosta, J. G., Karatas, A., & Derrible, S. (2023). The Role of Socio-Demographic and Economic Characteristics on Energy-Related Occupant Behavior. Journal of Building Eng, 106875.",
            "Palani, H., & Karatas, A. (2023). Innovative Environmental Chamber Construction for Accurate Thermal Performance Evaluation of Building Envelopes in Varied Climates. Buildings, 13(5), 1259.",
            "Acosta, J. G., Palani, H., Movahedi, A., Karatas, A., & Derrible, S. (2023). Residential Electricity Consumption Patterns and their Relationship to Commute Times by Mode. Findings.",
            "Palani, H., Khaleghi, H., Salehi, P., & Karatas, A. (2023). Assessing Hygrothermal Performance in Building Walls Engineered for Extreme Cold Climate Environments. Sustainability, 15(24), 16597.",
            "Rener, A., Karatas, A., & Videan, B. (2022). Innovative Design and Execution Model for Improving Productivity of Interior Prefabricated Commercial Wall Assemblies. Buildings, 13(1), 68.",
            "Palani, H., & Karatas, A. (2022). Holistic Approach for Reducing Occupants’ Energy Consumption in Hotel Buildings. Journal of Cleaner Production, 365, 132679.",
            "Palani, H., & Karatas, A. (2021). “Identifying Energy-Use Behavior and Energy-Use Profiles of Hotel Guests”. Applied Sciences, 11(13), 6093.",
            "Li, Da, Carol C. Menassa, and Karatas, A. (2017) “Energy Use Behaviors in Buildings: Towards an İntegrated Conceptual Framework.” Energy Research & Social Science 23: 97-112.",
            "Karatas, A. & El-Rayes, K. (2016) “Optimal Tradeoffs between Housing Cost and Environmental Performance.” Journal of Architectural Engineering, 04015018.",
            "Karatas, A., Stoiko, A., & Menassa, C. C. (2016). “Framework for Selecting Occupancy-Focused Energy İnterventions in Buildings”. Building Research & Information, 44(5-6), 535-551",
            "Karatas, A., & El-Rayes, K. (2015). “Evaluating the Performance of Sustainable Development in Urban Neighborhoods Based on the Feedback of Multiple Stakeholders”. Sustainable Cities and Society, 14, 374-382. ",
            "Karatas, A. & El-Rayes, K. (2015) “Optimizing Tradeoffs among Housing Sustainability Objectives”, Automation in Construction, Elsevier 53: 83-94.",
            "Karatas, A., & El-Rayes, K. (2015). “Parallel Computing Framework for Optimizing Environmental and Economic Performances of Housing Units”. Journal of Computing in Civil Engineering, 04015026.",
            "Karatas, A., & El-Rayes, K. (2014) “Optimal Trade-Offs between Social Quality of Life and Life-Cycle Cost in Housing Units”. Journal of Construction Engineering and Management 140.12.",
        ]
    },
    {   
        aKey: "book",
        title: "Book Chapters",
        content: [
            "Alsharif S., Karatas, A., ‘Data-Driven Approach For Improving Schedule and Cost Estimation of Nuclear Power Plant Projects, Nuclear Power Plants: Recent Progress and Future Directions. Nova Science Publiswea, 2022. ISBN: 978-1-68507-686-3",
            "Karatas, A., Stoiko, A., & Menassa, C. C.. ‘Framework for selecting occupancy-focused energy interventions in buildings’, Building Governance and Climate Change, 2019. 535-551",
            "Karatas, A., Stoiko, A., & Menassa, C. C.. ‘A Framework to Achieve Large Scale Energy Savings for Building Stocks through Targeted Occupancy Interventions: Foundations, Principles, and Applications.’ Smart Cities: Foundations, Principles, and Applications. John Wiley & Sons, 2017. doi: 10.1002/9781119226444.ch17",
        ]
    },
    {
        aKey: "conference",
        title: "Peer-Reviewed Conference Publications",
        content: [
            "Palani, H. and Karatas, A., and Tayor T. (2024) “Cost-Effective Hot Box Apparatus to Measure Thermal Performance of Building Envelopes”, CRC 2024 Conference (Accepted).",
            "Khaleghi, H and Karatas, A., (2024) “Experimental Framework to Measure Dynamic Thermal Resilience of Wall Panels under Extreme Weather Conditions”, CRC 2024 Conference (Accepted).",
            "Luna H., Palani, H., and Karatas, A., 2023 “Cost-Effective, Scalable and User-Friendly Temperature Control System for Measuring Thermal Performance of Building Envelope Systems in Environmental Chambers”, I3 Computing in Civil Engineering, (Accepted)",
            "Khaleghi, H and Karatas, A., (2023) “Arctic Architectures: Unleashing Energy Efficiency and Resilience in Extreme Cold Regions”, ISEC - 12. Chicago, US(In press).",
            "Palani, H., Acosta J., Karatas, A., and Derrible, S. (2023) “Predicting Energy Use Intensity of US Hotel Buildings Using CBECS Microdata”, ASCE Inspire (Abstract Accepted",
            "Palani, H. and Karatas, A., and Tayor T. (2024) “Cost-Effective Hot Box Apparatus to Measure Thermal Performance of Building Envelopes”, CRC 2024 Conference (Abstract Accepted).",
            "Khaleghi, H and Karatas, A., (2024) “Experimental Framework to Measure Dynamic Thermal Resilience of Wall Panels under Extreme Weather Conditions”, CRC 2024 Conference (Abstract Accepted).",
            "Rener, A., Karatas, A., and Cole, Matt, (2022) “Innovative Model for Forecasting Trailer Usage for Prefabricated Exterior Wall Panels”, ISARC 2022, Bogota, Colombia.",
            "Palani, H., Acosta J., Karatas, A., and Derrible, S. (2022) “Understanding the Interrelationship between Energy-Use Behavior and Socio-Demographic Profile”, ITISE-2022, Gran Canaria, Spain.",
            "Palani, H. and Karatas, A., (2022) “Integrated Energy-Use Model to Identify Energy-Use Profile of Hotel Guests”, Computing in Civil Engineering Orlando, FL, 688-695",
            "Palani, H. and Karatas, A., (2021) “Identifying Energy Use Behaviors of Hotel Guests”, CSCE 2021.",
            "Karatas, A., & Al-Sharif, S., (2020). Schedule and Cost Forecasting Model for Nuclear Power Plant Projects. In Construction Research Congress 2020: Project Management and Controls, Materials, and Contracts (pp. 721-729). Reston, VA: American Society of Civil Engineers.",
            "Palani, H. and Karatas, A., (2020) “Reducing Occupants Energy Consumptions in Hotel Buildings” Building Performance Analysis Conference and SimBuild, ASHRAE and IBPSA-USA.",
            "Albayati A. and Karatas, A. (2019) “Fall Prevention Supplementary Devices for Bridge Construction Workers: A Life Cycle Cost Analysis”, Proceedings of the Canadian Society for Civil Engineering International Construction Specialty Conference (ICSC’19), Montreal, Canada.",
            "Staple N. and Karatas, A. (2019) “A Study of the U.S. RoofingIndustryand its Workforce”, Proceedings of the Canadian Society for Civil Engineering International Construction Specialty Conference (ICSC’19), Montreal, Canada.",
            "Alwerfalli, D., Karatas, A., & Alshammari, M. (2017). “Application of quality management systems (QMS) in construction industry”. In Proceedings of the International Conference on Industrial Engineering and Operations Management (p. 46).",
            "Alsharif, S. and Karatas, A. “A Framework for Identifying Causal Factors of Delay in Nuclear Power Plant Projects.”Procedia Engineering145 (2016): 1486-1492.",
            "Karatas, A, Carol C. Menassa, and Allisandra Stoiko. (2015)”A Framework for Delivering Targeted Occupancy Interventions to Reduce Energy Usage in Buildings.” Procedia Engineering",
            "Karatas, A., and El-Rayes, K. (2014) ‘Optimal Configurations of Design and Construction Decisions for Maximizing Social Quality-of-Life for Housing Residents’. Construction Research Congress (CRC) 2014: pp. 436-443. doi: 10.1061/9780784413517.045.",
            "Karatas, A., and El-Rayes, K. (2014) “Maximizing Occupants Comfort in Affordable Housing Units.”Computing in Civil and Building Engineering 2040-2046). ASCE. doi: 10.1061/9780784413616.253.",
            "Karatas, A. and El-Rayes, K. (2012) ‘Evaluating and Quantifying Sustainable Development in Urban Neighborhoods’ ICSDEC 2012: pp. 214-221. doi: 10.1061/9780784412688.025.",
        ]
    },
]